### ISSUE TITLE
feed://kinozal.tv/rss.xml

### ISSUE THREAD

**Issue by vitasllc** [barisusakli/nodebb-plugin-rss#25]
Not work with:
feed://kinozal.tv/rss.xml

25/3 17:00 [18179] - info: [plugin-rss] posting, http://kinozal.tv/rss.xml - title: Радио Кинозал.ТВ. Клавдия Шульженко  Легенда времени  / 2016 / Радиопередача / MP3, published date: 2016-03-25T19:43:05Z
TypeError: Cannot read property 'replace' of undefined
    at Object.<anonymous> (/var/www/nodebb/node_modules/nodebb-plugin-rss/node_modules/string/lib/string.js:354:14)
    at multiArgs (/var/www/nodebb/node_modules/nodebb-plugin-rss/node_modules/string/lib/string.js:701:17)
    at S.stripTags (/var/www/nodebb/node_modules/nodebb-plugin-rss/node_modules/string/lib/string.js:353:7)
    at Command.callback (/var/www/nodebb/node_modules/nodebb-plugin-rss/index.js:195:43)
    at RedisClient.return_reply (/var/www/nodebb/node_modules/redis/index.js:664:25)
    at JavascriptReplyParser.reply_parser.send_reply (/var/www/nodebb/node_modules/redis/index.js:332:14)
    at JavascriptReplyParser.run (/var/www/nodebb/node_modules/redis/lib/parsers/javascript.js:132:18)
    at JavascriptReplyParser.execute (/var/www/nodebb/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/var/www/nodebb/node_modules/redis/index.js:131:27)
    at emitOne (events.js:77:13)

**Comment by vitasllc** [comment]
Solved
