### ISSUE TITLE
Error Happened while I use atom

### ISSUE THREAD

**Issue by Xuanwo** [barisusakli/nodebb-plugin-rss#28]
The log are look like this : 

```
14/7 04:00 [8664] - [32minfo[39m: [plugin-rss] posting, https://log.qingcloud.com/?feed=atom - title: [object Object], published date: 2016-07-11T03:49:23Z
14/7 04:00 [8664] - [31merror[39m: TypeError: data.title.trim is not a function
    at Object.Topics.post (/qingcloud/bbs/repo/qingcloud-community/src/topics/create.js:86:39)
    at Command.callback (/qingcloud/bbs/repo/qingcloud-community/node_modules/nodebb-plugin-rss/index.js:220:11)
    at RedisClient.return_reply (/qingcloud/bbs/repo/qingcloud-community/node_modules/redis/index.js:664:25)
    at JavascriptReplyParser.reply_parser.send_reply (/qingcloud/bbs/repo/qingcloud-community/node_modules/redis/index.js:332:14)
    at JavascriptReplyParser.run (/qingcloud/bbs/repo/qingcloud-community/node_modules/redis/lib/parsers/javascript.js:132:18)
    at JavascriptReplyParser.execute (/qingcloud/bbs/repo/qingcloud-community/node_modules/redis/lib/parsers/javascript.js:107:10)
    at Socket.<anonymous> (/qingcloud/bbs/repo/qingcloud-community/node_modules/redis/index.js:131:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
```

My feed is `https://log.qingcloud.com/?feed=atom` ，which tested ok on yql with 

```
select entry FROM feednormalizer where url='https://log.qingcloud.com/?feed=atom'
```

**Comment by Xuanwo** [comment]
Use RSS2, problem fixed.
